apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: raspi-monitor
spec:
  selector:
    matchLabels:
      app: raspi-monitor
  template:
    metadata:
      labels:
        app: raspi-monitor
    spec:
      containers:
      - name: raspberrymonitor
        image: saifwsm/raspberrymonitor:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName